export const galleryStyles = {
  root: 'space-y-6',
  title: 'text-2xl sm:text-3xl font-bold tracking-tight',
  subtitle: 'text-muted mt-1',
  filterBar: 'flex flex-wrap gap-2 -mt-1',
  filterChip: (active: boolean) =>
    `inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
      active
        ? 'bg-primary text-white border-primary'
        : 'bg-surface-2 text-muted border-border hover:text-foreground hover:border-primary/40'
    }`,
  filterCount: 'opacity-70 tabular-nums',
  loadingWrap: 'flex items-center justify-center py-20 text-muted',
  loadingIcon: 'h-6 w-6 animate-spin',
  emptyCard: 'p-10 sm:p-16 flex flex-col items-center text-center',
  emptyIconWrap: 'h-12 w-12 rounded-2xl bg-surface-2 flex items-center justify-center mb-3',
  emptyIcon: 'h-6 w-6 text-muted',
  emptyText: 'text-muted text-sm',
  emptyLink: 'mt-4 btn-glow inline-flex items-center gap-2 px-4 py-2 rounded-xl text-white text-sm font-medium',
  emptyLinkInner: 'relative z-10 inline-flex items-center gap-2',
  emptyLinkIcon: 'h-4 w-4',
  grid: 'grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4',
  gridItem: 'group relative aspect-square rounded-2xl overflow-hidden border border-border bg-surface-2 cursor-pointer transition-colors hover:border-primary/40',
  gridImg: 'w-full h-full object-cover transition-transform duration-300 group-hover:scale-105',
  processing: 'w-full h-full flex flex-col items-center justify-center gap-1 text-xs text-muted',
  processingIcon: 'h-4 w-4 animate-spin',
  menuBtn: 'absolute top-2 right-2 h-8 w-8 inline-flex items-center justify-center rounded-lg bg-black/45 backdrop-blur text-white opacity-100 lg:opacity-0 lg:group-hover:opacity-100 transition-opacity hover:bg-black/65',
  menuBtnIcon: 'h-4 w-4',
  downloadBtn: 'absolute bottom-2 right-2 h-8 w-8 inline-flex items-center justify-center rounded-lg bg-black/45 backdrop-blur text-white opacity-100 lg:opacity-0 lg:group-hover:opacity-100 transition-opacity hover:bg-black/65',
  downloadBtnIcon: 'h-4 w-4',
  dropdownOverlay: 'fixed inset-0 z-[90]',
  dropdown: 'fixed z-[91] w-44 rounded-xl p-1.5 bg-surface-solid border border-border shadow-2xl backdrop-blur-xl animate-scale-in',
  dropdownItem: (danger?: boolean) =>
    `w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm transition-colors ${
      danger ? 'text-danger hover:bg-danger/10' : 'text-foreground hover:bg-foreground/[0.06]'
    }`,
  dropdownItemIcon: 'h-4 w-4',
  previewOverlay: 'fixed inset-0 z-[100] bg-black/80 backdrop-blur-md flex flex-col p-4 animate-fade-in',
  previewClose: 'flex justify-end shrink-0',
  previewCloseBtn: 'h-10 w-10 inline-flex items-center justify-center rounded-xl text-white/80 hover:text-white hover:bg-white/10 transition-colors',
  previewCloseIcon: 'h-5 w-5',
  previewImgWrap: 'flex-1 min-h-0 flex items-center justify-center',
  previewImg: 'max-h-full max-w-full object-contain rounded-2xl animate-scale-in',
  previewActions: 'shrink-0 flex items-center justify-center gap-2 sm:gap-2.5 pt-4',
  previewActionIcon: 'h-4 w-4',
  previewActionInline: 'hidden sm:inline',
  modalBody: 'px-5 pb-5 pt-2 space-y-4',
  modalDivider: 'h-px bg-border',
  detailHeader: 'flex items-center justify-between mb-1',
  detailLabel: 'text-xs text-muted uppercase tracking-wider',
  detailCopyBtn: 'inline-flex items-center gap-1 text-xs text-muted hover:text-primary transition-colors',
  detailCheckIcon: 'h-3.5 w-3.5 text-success',
  detailCopyIcon: 'h-3.5 w-3.5',
  detailValue: 'text-sm break-words',
};
