export const loginStyles = {
  root: 'min-h-screen bg-background text-foreground flex items-center justify-center px-4 relative overflow-hidden',
  themeToggleWrap: 'absolute top-4 right-4 z-20',
  card: 'relative z-10 w-full max-w-md animate-scale-in',
  head: 'flex flex-col items-center mb-8',
  title: 'text-2xl font-bold tracking-tight mt-5',
  subtitle: 'text-muted mt-1 text-sm',
  panel: 'glass glow-border rounded-2xl p-7 sm:p-8',
  googleBtn: 'mb-6',
  dividerWrap: 'relative mb-6',
  dividerLineWrap: 'absolute inset-0 flex items-center',
  dividerLine: 'w-full border-t border-border',
  dividerTextWrap: 'relative flex justify-center',
  dividerText: 'px-3 bg-surface-solid text-xs text-muted rounded-full',
  form: 'space-y-4',
  error: 'flex items-center gap-2 p-3 bg-danger/10 border border-danger/20 rounded-xl text-danger text-sm animate-fade-in',
  errorIcon: 'h-4 w-4 shrink-0',
  label: 'block text-sm font-medium mb-1.5',
  fieldError: 'mt-1.5 flex items-center gap-1.5 text-xs text-danger',
  fieldErrorIcon: 'h-3.5 w-3.5 shrink-0',
  footerText: 'mt-6 text-center text-sm text-muted',
  footerLink: 'text-primary hover:text-primary-hover font-medium',
  googleMark: 'h-4 w-4',
};
