export const dashboardStyles = {
  root: 'space-y-9 animate-fade-in-up',
  heading: 'text-3xl sm:text-4xl font-extrabold tracking-tight',
  headingName: 'text-gradient',
  headingSub: 'text-muted mt-1.5',
  sectionLabel: 'text-xs font-semibold text-muted uppercase tracking-[0.15em] mb-3',
  actionsGrid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4',
  faceIcon: 'h-5 w-5 text-white/90',
  card: 'p-5 h-full group cursor-pointer',
  cardRow: 'flex items-center gap-4',
  cubeWrap: 'shrink-0 transition-transform duration-300 group-hover:scale-110',
  cardBody: 'min-w-0',
  cardTitle: 'font-semibold text-sm flex items-center gap-1.5',
  cardArrow: 'h-3.5 w-3.5 text-primary opacity-0 -translate-x-1 group-hover:opacity-100 group-hover:translate-x-0 transition-all',
  cardDesc: 'text-xs text-muted mt-0.5',
  recentHeader: 'flex items-center justify-between mb-3',
  recentLabel: 'text-xs font-semibold text-muted uppercase tracking-[0.15em]',
  viewAllLink: 'text-sm text-primary hover:text-primary-hover font-medium flex items-center gap-1',
  viewAllIcon: 'h-3.5 w-3.5',
  emptyCard: 'px-6 py-7 flex items-center gap-4',
  emptyCubeWrap: 'shrink-0',
  sparkleFaceIcon: 'h-4 w-4 text-white/90',
  emptyBody: 'flex-1 min-w-0',
  emptyTitle: 'text-sm font-medium',
  emptyDesc: 'text-xs text-muted',
  emptyLink: 'btn-glow shrink-0 inline-flex items-center gap-2 px-4 py-2 rounded-xl text-white text-sm font-medium',
  emptyLinkInner: 'relative z-10 inline-flex items-center gap-2',
  emptyLinkIcon: 'h-4 w-4',
  recentRow: 'flex gap-3 overflow-x-auto pb-2 -mx-1 px-1 [scrollbar-width:none]',
  recentLink: 'group relative block h-28 w-28 sm:h-32 sm:w-32 shrink-0 rounded-xl overflow-hidden border border-border bg-surface-2',
  recentImg: 'w-full h-full object-cover transition-transform duration-300 group-hover:scale-110',
};
